### ISSUE TITLE
Add Github issue template

### ISSUE THREAD

**Issue by corburn** [caporaso-lab/An-Introduction-To-Applied-Bioinformatics#269]
A possible followup to #268 (ENH: add note requesting that users report version with issues)

could be to add a Github issue template prompting users with information to include:

https://github.com/blog/2111-issue-and-pull-request-templates

**Comment by gregcaporaso** [comment]
Good idea, thanks @corburn! I'm interested in doing that (and would also be interested in PR if you'd like to take a crack at it).

**Comment by khdc-me** [comment]
I'd like to take ownership of this if still available.

Is there anything that you'd like to prompt user for besides IAB, OS, and Conda version?

**Comment by corburn** [comment]
Would you suggest any edits to #270?

**Comment by khdc-me** [comment]
Whoops, didn't see it.

The template looks good. Maybe also prompt user for OS (distro and version) and conda version?
